[platformio]
src_dir = .

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
upload_protocol = teensy-cli   ; <--- ADD THIS LINE
build_src_filter = +<*> -<teensy_coinft_serial_interface_3CFT.cpp>

[env:teensy40_3cft]
platform = teensy
board = teensy40
framework = arduino
upload_protocol = teensy-cli
build_src_filter = +<*> -<teensy_coinft_serial_interface.cpp>
